export enum EventTypes {
    UPLOAD_FILE = 'UPLOAD_FILE',
    UPLOAD_SCHEMA = 'UPLOAD_SCHEMA',
    DRONE_AUTH = 'DRONE_AUTH',
    SEND_DATA = 'SEND_DATA',
    SCHEMAS_RECEIVED = 'SCHEMAS_RECEIVED',
    HANDLE_TOPICS = 'HANDLE_TOPICS',
    GET_DRONES = 'GET_DRONES',
    REDIRECT = 'REDIRECT',
    SEND_FILE = 'SEND_FILE',
    LOGOUT = 'LOGOUT',
}